import { expect, test } from "@playwright/test"

test("older layout preferences open the full-screen wall with one exit", async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem("personal-photos-layout", "grid"))
  await page.emulateMedia({ reducedMotion: "reduce" })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto("/")
  await page.locator(".personal-photos-label").click()
  const dialog = page.getByRole("dialog", { name: "Personal photos" })
  const wall = dialog.getByRole("region", { name: "Photo wall" })
  await expect(wall).toBeVisible()
  expect(await wall.boundingBox()).toEqual({ x: 0, y: 0, width: 390, height: 844 })
  await expect(dialog.getByRole("group", { name: "Layout" })).toHaveCount(0)
  await expect(dialog.getByRole("button")).toHaveCount(1)
  const close = dialog.getByRole("button", { name: "Close photo wall" })
  const closeBox = (await close.boundingBox())!
  expect(closeBox.height).toBeGreaterThanOrEqual(44)
  await expect(close).toHaveAccessibleName("Close photo wall")
  await expect(close.locator("kbd")).toHaveCount(0)
  await expect(close.locator("svg")).toBeVisible()
  expect(await close.evaluate(element => getComputedStyle(element, "::before").content)).toBe("none")
  expect(await close.evaluate(element => getComputedStyle(element).boxShadow)).not.toBe("none")
  await page.mouse.move(closeBox.x + closeBox.width / 2, closeBox.y + closeBox.height / 2)
  await page.mouse.down()
  expect(await close.evaluate(element => getComputedStyle(element).scale)).toBe("0.96")
  await page.mouse.move(0, 0)
  await page.mouse.up()
  const photo = wall.locator(".personal-photos-slide[data-photo-id]").first()
  await photo.focus()
  await page.keyboard.press("Enter")
  await expect(photo).toHaveAttribute("data-held", "")
  await page.keyboard.press("Escape")
  await expect(photo).not.toHaveAttribute("data-held", "")
  await close.click()
  await expect(dialog).toBeHidden()
})

test("Escape returns focus without leaving the Personal life tile visibly selected", async ({ page }) => {
  await page.emulateMedia({ reducedMotion: "reduce" })
  await page.goto("/")
  const trigger = page.getByRole("button", { name: "Personal life", exact: true })

  await trigger.click()
  await expect(page.getByRole("dialog", { name: "Personal photos" })).toBeVisible()
  await page.keyboard.press("Escape")

  await expect(page.getByRole("dialog", { name: "Personal photos" })).toBeHidden()
  await expect(trigger).toBeFocused()
  await expect(trigger).toHaveCSS("outline-style", "none")
  await page.keyboard.press("Tab")
  await expect(trigger).not.toHaveAttribute("data-photo-focus-return")
  await page.keyboard.press("Shift+Tab")
  await expect(trigger).toBeFocused()
  await expect(trigger).toHaveCSS("outline-style", "solid")
})
