import { expect, test } from "@playwright/test"

test.beforeEach(async ({ page }) => {
  await page.emulateMedia({ reducedMotion: "reduce" })
})

test("writing URLs follow selection and browser Back and Forward", async ({ page }) => {
  await page.goto("/?ref=portfolio")
  const folder = page.getByRole("button", { name: "Open writings folder" })
  await folder.click()
  const dialog = page.getByRole("dialog")
  await dialog.getByRole("button", { name: "Designing Matcha", exact: true }).click()
  await expect(page).toHaveURL(/\?ref=portfolio&writing=designing-matcha$/)
  await dialog.getByRole("button", { name: "Next note", exact: true }).click()
  await expect(page).toHaveURL(/writing=designing-for-active-traders$/)
  await page.goBack()
  await expect(dialog).toBeHidden()
  await expect(page).toHaveURL(/\?ref=portfolio$/)
  await expect(folder).toBeFocused()
  await page.goForward()
  await expect(dialog.getByRole("heading", { name: "Designing for active traders", exact: true })).toBeVisible()
  await page.keyboard.press("Escape")
  await expect(dialog).toBeHidden()
  await expect(page).toHaveURL(/\?ref=portfolio$/)
})

test("a shared writing opens after hydration and refresh and closes locally", async ({ page }) => {
  const errors: string[] = []
  page.on("pageerror", error => errors.push(error.message))
  await page.goto("/?ref=shared&writing=designing-matcha")
  const title = page.getByRole("heading", { name: "Designing Matcha", exact: true })
  await expect(title).toBeVisible()
  await page.reload()
  await expect(title).toBeVisible()
  await page.getByRole("button", { name: "Notes", exact: true }).click()
  await expect(page).toHaveURL(/\?ref=shared$/)
  await expect(page.getByRole("button", { name: "Designing Matcha", exact: true })).toBeFocused()
  await page.keyboard.press("Escape")
  await expect(page.getByRole("dialog")).toBeHidden()
  await expect(page).toHaveURL(/\?ref=shared$/)
  expect(errors).toEqual([])
})

test("returning to notes clears the writing URL and closing consumes its history entry", async ({ page }) => {
  await page.goto("/?from=previous")
  await page.goto("/?ref=portfolio")
  await page.getByRole("button", { name: "Open writings folder" }).click()
  const dialog = page.getByRole("dialog")
  const entry = dialog.getByRole("button", { name: "Designing Matcha", exact: true })
  await entry.click()
  await dialog.getByRole("button", { name: "Notes", exact: true }).click()
  await expect(page).toHaveURL(/\?ref=portfolio$/)
  await expect(entry).toBeFocused()
  await entry.click()
  await expect(page).toHaveURL(/writing=designing-matcha$/)
  await page.keyboard.press("Escape")
  await expect(dialog).toBeHidden()
  await expect(page).toHaveURL(/\?ref=portfolio$/)
  await page.goBack()
  await expect(page).toHaveURL(/\?from=previous$/)
})

test("an unknown writing leaves the folder usable", async ({ page }) => {
  await page.goto("/?writing=missing")
  await expect(page.getByRole("dialog")).toHaveCount(0)
  await page.getByRole("button", { name: "Open writings folder" }).click()
  await page.getByRole("button", { name: "Designing Matcha", exact: true }).click()
  await expect(page).toHaveURL(/writing=designing-matcha$/)
  await page.keyboard.press("Escape")
  await expect(page.getByRole("dialog")).toBeHidden()
  await expect(page).toHaveURL(/\/$/)
})
