import { expect, test, type Page } from '@playwright/test'

const openAbout = async (page: Page) => {
  await page.goto('/?introStyle=a')
  await page.locator('#about-panel').evaluate(node => node.scrollIntoView({ behavior: 'instant' }))
  const intro = page.getByRole('region', { name: 'A quick hello from Rafael' })
  await expect(intro).toBeVisible()
  return intro
}

test('reveals play on the portrait and offers email and text tooltips', async ({ page }) => {
  const intro = await openAbout(page)
  await expect(intro.locator('.about-intro-play-mark')).toHaveCSS('opacity', '0')
  await intro.getByRole('button', { name: 'Show introduction actions' }).hover()
  await expect(intro.locator('.about-intro-play-mark')).toHaveCSS('opacity', '1')
  const email = intro.getByRole('button', { name: 'Your email', exact: true })
  await email.hover()
  await expect(intro.getByRole('tooltip', { name: 'Your email', exact: true })).toBeVisible()
  await expect(email).toHaveCSS('width', '128px')
  await expect(intro.locator('.about-intro-actions')).toHaveCSS('width', '184px')
  const text = intro.getByRole('button', { name: 'Text me', exact: true })
  await text.hover()
  await expect(text).toHaveCSS('width', '128px')
  await expect(email).toHaveCSS('width', '44px')
  await expect(intro.getByRole('tooltip', { name: 'Text me', exact: true })).toBeVisible()
  await expect(intro.getByRole('button', { name: 'Text me', exact: true })).toBeVisible()
  await expect(intro.getByRole('button', { name: 'Reply on video' })).toHaveCount(0)
})

test('opens a minimal email input with an arrow and returns focus on escape', async ({ page }) => {
  const intro = await openAbout(page)
  await intro.hover()
  await intro.getByRole('button', { name: 'Your email', exact: true }).click()
  const panel = intro.getByRole('region', { name: 'Email reply' })
  const email = panel.getByRole('textbox', { name: 'Your email' })
  await expect(email).toBeFocused()
  await expect(panel.getByRole('textbox')).toHaveCount(1)
  await expect(panel.getByRole('button')).toHaveCount(0)
  const send = panel.locator('.about-intro-send')
  await expect(send).toHaveCSS('opacity', '0')
  await expect(email).toHaveAttribute('placeholder', 'hello@example.com')
  await email.fill('asda@asd.')
  await expect(send).toBeDisabled()
  await expect(send).toHaveCSS('opacity', '1')
  await expect(panel.locator('header, p')).toHaveCount(0)
  const arrow = panel.getByRole('button', { name: 'Open email draft' })
  const inputBox = await email.boundingBox()
  const arrowBox = await arrow.boundingBox()
  const portraitBox = await intro.locator('.about-intro-surface').boundingBox()
  await expect.poll(async () => (await panel.boundingBox())!.x).toBeGreaterThan(portraitBox!.x + portraitBox!.width)
  expect(await panel.locator('..').getAttribute('class')).toBe('about-intro-actions')
  await expect(intro.getByRole('button', { name: 'Dismiss introduction' })).toHaveCount(0)
  expect(arrowBox!.x).toBeGreaterThan(inputBox!.x)
  expect(Math.abs(inputBox!.y - arrowBox!.y)).toBeLessThan(4)
  await email.press('Enter')
  await expect(email).toBeFocused()
  await email.fill('hello@example.com')
  await expect(arrow).toBeEnabled()
  await expect.poll(() => arrow.evaluate(node => getComputedStyle(node, '::before').backgroundColor)).toBe('rgb(0, 122, 255)')
  await page.keyboard.press('Escape')
  await expect(intro.getByRole('button', { name: 'Your email', exact: true })).toBeFocused()
  await expect(intro.locator('video[data-recording]')).not.toHaveAttribute('src')
})

test('opens a compact text composer and keeps delivery explicit', async ({ page }) => {
  const intro = await openAbout(page)
  await intro.hover()
  await intro.getByRole('button', { name: 'Text me', exact: true }).click()
  const panel = intro.getByRole('region', { name: 'Text reply' })
  await expect(panel.getByRole('textbox', { name: 'Your message' })).toBeFocused()
  await panel.getByRole('textbox', { name: 'Your message' }).fill('A question & an idea?')
  await panel.getByRole('textbox', { name: 'Your email' }).fill('hello+site@example.com')
  await expect(panel.getByRole('button', { name: 'Open email draft' })).toHaveAttribute('title', 'Review and send in your email app')
  await page.mouse.click(310, 100)
  await expect(panel).toHaveCount(0)
  const text = intro.getByRole('button', { name: 'Text me', exact: true })
  await expect(text).toBeVisible()
  await expect(text).toHaveCSS('width', '128px')
  await expect(text).not.toBeFocused()
  await text.click()
  await expect(panel.getByRole('textbox', { name: 'Your message' })).toHaveValue('A question & an idea?')
})

test.describe('touch layout', () => {
  test.use({ hasTouch: true, isMobile: true })

test('toggles video controls by tapping the video on touch screens', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 740 })
  const intro = await openAbout(page)
  await intro.getByRole('button', { name: 'Show introduction actions' }).tap()
  await intro.getByRole('button', { name: 'Play introduction', exact: true }).tap()
  await expect(intro.locator('.about-intro-controls')).toHaveCSS('opacity', '1')
  await intro.getByRole('button', { name: 'Pause introduction' }).tap()
  await intro.getByRole('button', { name: 'Hide video controls' }).tap({ position: { x: 100, y: 80 } })
  await expect(intro.locator('.about-intro-controls')).toHaveCSS('opacity', '0')
  await intro.getByRole('button', { name: 'Show video controls' }).tap({ position: { x: 100, y: 80 } })
  await expect(intro.locator('.about-intro-controls')).toHaveCSS('opacity', '1')
  await expect(intro.getByRole('button', { name: 'Resume introduction' })).toBeVisible()
  await intro.getByRole('button', { name: 'Close introduction' }).tap()
  await expect(intro).toHaveAttribute('data-open', 'false')
})

test('keeps minimal email controls together at 320px', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 740 })
  const intro = await openAbout(page)
  await intro.getByRole('button', { name: 'Show introduction actions' }).tap()
  await intro.getByRole('button', { name: 'Your email', exact: true }).click()
  const panel = intro.getByRole('region', { name: 'Email reply' })
  const box = await panel.boundingBox()
  expect(box!.x).toBeGreaterThanOrEqual(12)
  expect(box!.x + box!.width).toBeLessThanOrEqual(308)
  expect(box!.height).toBeLessThanOrEqual(64)
  const portrait = await intro.locator('.about-intro-surface').boundingBox()
  expect(box!.x).toBeGreaterThanOrEqual(portrait!.x + portrait!.width + 8)
  await panel.getByRole('textbox', { name: 'Your email' }).fill('hello@example.com')
  await page.setViewportSize({ width: 320, height: 420 })
  await expect(panel.getByRole('button', { name: 'Open email draft' })).toBeInViewport()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(320)
  await page.mouse.click(20, 100)
  const button = intro.getByRole('button', { name: 'Your email', exact: true })
  await expect(button).toBeVisible()
  await expect(button).toHaveCSS('width', '128px')
  const actions = await intro.locator('.about-intro-actions').boundingBox()
  expect(actions!.x).toBeGreaterThanOrEqual(12)
  expect(actions!.x + actions!.width).toBeLessThanOrEqual(308)
})

})

test('shows the hello on hover and fills the player with edge-to-edge video', async ({ page }) => {
  const intro = await openAbout(page)
  await expect(intro.locator('.about-intro-label')).toHaveCSS('opacity', '0')
  await intro.hover()
  await expect(intro.locator('.about-intro-label')).toHaveCSS('opacity', '1')
  await expect(intro.locator('.about-intro-label')).not.toContainText('Placeholder')
  await intro.getByRole('button', { name: 'Play introduction', exact: true }).click()
  await expect(intro.getByRole('button', { name: 'Pause introduction' })).toBeVisible()
  const surface = intro.locator('.about-intro-surface')
  const video = intro.locator('video[data-recording]')
  await expect(surface).toHaveCSS('width', '240px')
  await expect(video).toHaveCSS('height', '240px')
  await expect(video).toHaveCSS('object-fit', 'cover')
  await intro.getByRole('button', { name: 'Expand introduction' }).click()
  await expect(surface).toHaveCSS('width', '480px')
  await intro.getByRole('button', { name: 'Shrink introduction' }).click()
  await expect(surface).toHaveCSS('width', '240px')
  await page.mouse.click(800, 100)
  await expect(intro.locator('.about-intro-controls')).toHaveCSS('opacity', '0')
  await surface.hover()
  await expect(intro.locator('.about-intro-controls')).toHaveCSS('opacity', '1')
  await intro.getByRole('button', { name: 'Close introduction' }).click()
  await expect(intro).toHaveAttribute('data-open', 'false')
})
