import { expect, test } from '@playwright/test'

for (const width of [390, 1440]) {
  test(`shares conversation between portrait and booking at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    await page.emulateMedia({ reducedMotion: 'reduce' })
    await page.route('https://cal.com/**', route => route.fulfill({ contentType: 'text/html', body: '<title>Calendar</title>' }))
    await page.goto('/?tune=off')
    await page.locator('.mosaic-avatar-button').click()
    const dialog = page.getByRole('dialog', { name: 'Chat with Rafael Medina' })
    await expect(dialog.getByRole('textbox', { name: 'Your email' })).toBeVisible()
    await expect(dialog.locator('iframe')).toHaveCount(0)
    await dialog.getByRole('textbox', { name: 'Your email' }).fill('visitor@example.com')
    await dialog.getByRole('button', { name: 'Continue with email' }).click()
    await dialog.getByRole('textbox', { name: 'Your message' }).fill('Let’s talk about a design project.')
    await dialog.getByRole('button', { name: 'Book a time', exact: true }).click()
    await expect(dialog.locator('iframe')).toHaveAttribute('src', /email=visitor%40example.com/)
    await expect(dialog.locator('iframe')).toHaveAttribute('src', /theme=light/)
    await dialog.getByRole('button', { name: 'Back to conversation' }).click()
    await expect(dialog.getByRole('textbox', { name: 'Your message' })).toHaveValue('Let’s talk about a design project.')
    await page.keyboard.press('Escape')
    await expect(page.locator('.mosaic-avatar-button')).toBeFocused()
    await page.locator('.mosaic-booking-pill').click()
    await expect(dialog.getByRole('textbox', { name: 'Your message' })).toHaveValue('Let’s talk about a design project.')
    const bounds = await dialog.boundingBox()
    expect(bounds!.x).toBeGreaterThanOrEqual(0)
    expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(width)
  })
}

test('retains failed messages and retries without duplicating delivery', async ({ page }) => {
  const requests: { email: string; message: string; requestId: string }[] = []
  await page.route('**/contact', async route => {
    requests.push(route.request().postDataJSON())
    await route.fulfill({ status: requests.length === 1 ? 503 : 200, json: requests.length === 1 ? { error: 'Please retry.' } : { sent: true } })
  })
  await page.goto('/?tune=off')
  await page.locator('.mosaic-booking-pill').click()
  const dialog = page.getByRole('dialog', { name: 'Chat with Rafael Medina' })
  await dialog.getByRole('textbox', { name: 'Your email' }).fill('visitor@example.com')
  await dialog.getByRole('button', { name: 'Continue with email' }).click()
  await dialog.getByRole('textbox', { name: 'Your message' }).fill('A new project')
  await dialog.getByRole('button', { name: 'Send message', exact: true }).click()
  await expect(dialog.getByRole('alert')).toContainText('Please retry.')
  await dialog.getByRole('button', { name: 'Retry message' }).click()
  await expect(dialog.getByText('Delivered', { exact: true })).toBeVisible()
  expect(requests).toHaveLength(2)
  expect(requests[0]).toEqual({ email: 'visitor@example.com', message: 'A new project', requestId: expect.any(String) })
  expect(requests[1]).toEqual(requests[0])
})

test('validates email and keeps controls reachable in a short mobile viewport', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 480 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/?tune=off')
  await page.locator('.mosaic-booking-pill').click()
  const dialog = page.getByRole('dialog', { name: 'Chat with Rafael Medina' })
  const email = dialog.getByRole('textbox', { name: 'Your email' })
  await email.fill('visitor@incomplete')
  await expect(dialog.getByRole('button', { name: 'Continue with email' })).toBeDisabled()
  await email.fill('visitor@example.com')
  await email.press('Enter')
  await expect(dialog.getByRole('textbox', { name: 'Your message' })).toBeFocused()
  await dialog.getByRole('button', { name: 'Change email' }).click()
  await expect(email).toBeFocused()
  await expect(email).toHaveValue('visitor@example.com')
  await expect(dialog).not.toHaveAttribute('aria-modal', 'true')
  await expect(page.locator('.booking-backdrop')).toHaveCount(0)
  await expect(dialog).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)')
  const box = await dialog.getByRole('button', { name: 'Continue with email' }).boundingBox()
  expect(box!.y + box!.height).toBeLessThan(480)
  await dialog.getByRole('button', { name: 'Close conversation' }).click()
  await expect(page.locator('.mosaic-booking-pill')).toBeFocused()
})

test('grows the floating conversation then scrolls history without locking the page', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.route('**/contact', route => route.fulfill({ json: { sent: true } }))
  await page.goto('/?tune=off')
  await page.locator('.mosaic-booking-pill').click()
  const dialog = page.getByRole('dialog', { name: 'Chat with Rafael Medina' })
  await expect(dialog.getByRole('textbox', { name: 'Your email' })).toBeVisible()
  const initial = await dialog.boundingBox()
  await dialog.getByRole('textbox', { name: 'Your email' }).fill('visitor@example.com')
  await dialog.getByRole('button', { name: 'Continue with email' }).click()
  await expect.poll(async () => (await dialog.boundingBox())!.height).toBeGreaterThan(initial!.height)
  for (let index = 0; index < 4; index++) {
    await dialog.getByRole('textbox', { name: 'Your message' }).fill(`Project detail ${index}: I’m building a new product and would love to talk about the design, onboarding, and the experience for our customers.`)
    await dialog.getByRole('button', { name: 'Send message', exact: true }).click()
    await expect(dialog.getByText('Delivered', { exact: true })).toHaveCount(index + 1)
  }
  const history = dialog.getByRole('log')
  expect(await history.evaluate(node => node.scrollHeight > node.clientHeight)).toBe(true)
  const composer = await dialog.getByRole('textbox', { name: 'Your message' }).boundingBox()
  expect(composer!.y + composer!.height).toBeLessThan(900)
  await page.mouse.move(50, 300)
  await page.mouse.wheel(0, 300)
  await expect.poll(() => page.evaluate(() => window.scrollY)).toBeGreaterThan(0)
  await expect(dialog).toBeVisible()
})
