// Generated by scripts/build-about-intro-placeholder.mjs.
import type { AboutIntroMedia } from "./aboutIntro"

export const aboutIntroPreview: AboutIntroMedia = {
  "placeholder": true,
  "duration": 50.6,
  "transcript": "Silent uploaded recording for testing the introduction player.",
  "assets": {
    "recording": "/tests/fixtures/about-intro/recording.mp4",
    "teaser": "/tests/fixtures/about-intro/teaser.gif",
    "poster": "/tests/fixtures/about-intro/poster.webp",
    "captions": "/tests/fixtures/about-intro/captions.vtt"
  }
}
