// GENERATED by scripts/build-github-activity.mjs -- do not edit by hand.
//
// @rafaelmedian's contribution calendar, fetched once and committed rather than
// requested at run time or at build time. The profile-wide graph is only
// available through GitHub's authenticated GraphQL API, so a live read would
// mean a token in CI; this is the same deal the résumé PDF makes, and it goes
// stale the same way. Re-run the script and commit the result.
//
// Fetched 2026-09-09.

/** A day in the calendar, or null for a cell the window does not cover. */
export type ContributionDay = { date: string; count: number } | null

export type ContributionCalendar = {
  login: string
  /** UTC `YYYY-MM-DD` the data was fetched, so staleness is visible in the diff. */
  fetchedOn: string
  total: number
  /** The busiest day in the window. */
  max: number
  /** Upper bound of shading bands 1, 2, and 3; anything above is band 4. */
  thresholds: [number, number, number]
  /** Weeks oldest-first, each seven days Sunday-first. */
  weeks: ContributionDay[][]
}

export const contributionCalendar: ContributionCalendar = {
  login: "rafaelmedian",
  fetchedOn: "2026-09-09",
  total: 1390,
  max: 102,
  thresholds: [5, 10, 19],
  weeks: [
    [null, { date: "2026-03-09", count: 0 }, { date: "2026-03-10", count: 0 }, { date: "2026-03-11", count: 0 }, { date: "2026-03-12", count: 0 }, { date: "2026-03-13", count: 1 }, { date: "2026-03-14", count: 2 }],
    [{ date: "2026-03-15", count: 1 }, { date: "2026-03-16", count: 0 }, { date: "2026-03-17", count: 8 }, { date: "2026-03-18", count: 0 }, { date: "2026-03-19", count: 5 }, { date: "2026-03-20", count: 0 }, { date: "2026-03-21", count: 0 }],
    [{ date: "2026-03-22", count: 0 }, { date: "2026-03-23", count: 0 }, { date: "2026-03-24", count: 0 }, { date: "2026-03-25", count: 0 }, { date: "2026-03-26", count: 0 }, { date: "2026-03-27", count: 0 }, { date: "2026-03-28", count: 0 }],
    [{ date: "2026-03-29", count: 3 }, { date: "2026-03-30", count: 11 }, { date: "2026-03-31", count: 7 }, { date: "2026-04-01", count: 5 }, { date: "2026-04-02", count: 6 }, { date: "2026-04-03", count: 6 }, { date: "2026-04-04", count: 2 }],
    [{ date: "2026-04-05", count: 12 }, { date: "2026-04-06", count: 13 }, { date: "2026-04-07", count: 1 }, { date: "2026-04-08", count: 4 }, { date: "2026-04-09", count: 3 }, { date: "2026-04-10", count: 0 }, { date: "2026-04-11", count: 0 }],
    [{ date: "2026-04-12", count: 0 }, { date: "2026-04-13", count: 0 }, { date: "2026-04-14", count: 8 }, { date: "2026-04-15", count: 10 }, { date: "2026-04-16", count: 6 }, { date: "2026-04-17", count: 0 }, { date: "2026-04-18", count: 0 }],
    [{ date: "2026-04-19", count: 1 }, { date: "2026-04-20", count: 1 }, { date: "2026-04-21", count: 12 }, { date: "2026-04-22", count: 0 }, { date: "2026-04-23", count: 0 }, { date: "2026-04-24", count: 0 }, { date: "2026-04-25", count: 0 }],
    [{ date: "2026-04-26", count: 0 }, { date: "2026-04-27", count: 0 }, { date: "2026-04-28", count: 0 }, { date: "2026-04-29", count: 0 }, { date: "2026-04-30", count: 0 }, { date: "2026-05-01", count: 0 }, { date: "2026-05-02", count: 0 }],
    [{ date: "2026-05-03", count: 0 }, { date: "2026-05-04", count: 0 }, { date: "2026-05-05", count: 0 }, { date: "2026-05-06", count: 0 }, { date: "2026-05-07", count: 0 }, { date: "2026-05-08", count: 0 }, { date: "2026-05-09", count: 0 }],
    [{ date: "2026-05-10", count: 0 }, { date: "2026-05-11", count: 0 }, { date: "2026-05-12", count: 0 }, { date: "2026-05-13", count: 0 }, { date: "2026-05-14", count: 0 }, { date: "2026-05-15", count: 0 }, { date: "2026-05-16", count: 0 }],
    [{ date: "2026-05-17", count: 0 }, { date: "2026-05-18", count: 0 }, { date: "2026-05-19", count: 0 }, { date: "2026-05-20", count: 0 }, { date: "2026-05-21", count: 0 }, { date: "2026-05-22", count: 0 }, { date: "2026-05-23", count: 0 }],
    [{ date: "2026-05-24", count: 0 }, { date: "2026-05-25", count: 1 }, { date: "2026-05-26", count: 0 }, { date: "2026-05-27", count: 0 }, { date: "2026-05-28", count: 0 }, { date: "2026-05-29", count: 0 }, { date: "2026-05-30", count: 0 }],
    [{ date: "2026-05-31", count: 0 }, { date: "2026-06-01", count: 0 }, { date: "2026-06-02", count: 0 }, { date: "2026-06-03", count: 0 }, { date: "2026-06-04", count: 0 }, { date: "2026-06-05", count: 0 }, { date: "2026-06-06", count: 0 }],
    [{ date: "2026-06-07", count: 0 }, { date: "2026-06-08", count: 0 }, { date: "2026-06-09", count: 0 }, { date: "2026-06-10", count: 0 }, { date: "2026-06-11", count: 0 }, { date: "2026-06-12", count: 0 }, { date: "2026-06-13", count: 0 }],
    [{ date: "2026-06-14", count: 0 }, { date: "2026-06-15", count: 0 }, { date: "2026-06-16", count: 3 }, { date: "2026-06-17", count: 0 }, { date: "2026-06-18", count: 0 }, { date: "2026-06-19", count: 0 }, { date: "2026-06-20", count: 0 }],
    [{ date: "2026-06-21", count: 0 }, { date: "2026-06-22", count: 3 }, { date: "2026-06-23", count: 0 }, { date: "2026-06-24", count: 0 }, { date: "2026-06-25", count: 18 }, { date: "2026-06-26", count: 3 }, { date: "2026-06-27", count: 16 }],
    [{ date: "2026-06-28", count: 34 }, { date: "2026-06-29", count: 34 }, { date: "2026-06-30", count: 6 }, { date: "2026-07-01", count: 19 }, { date: "2026-07-02", count: 39 }, { date: "2026-07-03", count: 12 }, { date: "2026-07-04", count: 26 }],
    [{ date: "2026-07-05", count: 63 }, { date: "2026-07-06", count: 100 }, { date: "2026-07-07", count: 102 }, { date: "2026-07-08", count: 78 }, { date: "2026-07-09", count: 64 }, { date: "2026-07-10", count: 71 }, { date: "2026-07-11", count: 54 }],
    [{ date: "2026-07-12", count: 15 }, { date: "2026-07-13", count: 20 }, { date: "2026-07-14", count: 10 }, { date: "2026-07-15", count: 0 }, { date: "2026-07-16", count: 0 }, { date: "2026-07-17", count: 19 }, { date: "2026-07-18", count: 10 }],
    [{ date: "2026-07-19", count: 14 }, { date: "2026-07-20", count: 6 }, { date: "2026-07-21", count: 22 }, { date: "2026-07-22", count: 28 }, { date: "2026-07-23", count: 6 }, { date: "2026-07-24", count: 3 }, { date: "2026-07-25", count: 0 }],
    [{ date: "2026-07-26", count: 1 }, { date: "2026-07-27", count: 39 }, { date: "2026-07-28", count: 4 }, { date: "2026-07-29", count: 10 }, { date: "2026-07-30", count: 14 }, { date: "2026-07-31", count: 12 }, { date: "2026-08-01", count: 0 }],
    [{ date: "2026-08-02", count: 0 }, { date: "2026-08-03", count: 6 }, { date: "2026-08-04", count: 0 }, { date: "2026-08-05", count: 8 }, { date: "2026-08-06", count: 0 }, { date: "2026-08-07", count: 0 }, { date: "2026-08-08", count: 0 }],
    [{ date: "2026-08-09", count: 0 }, { date: "2026-08-10", count: 0 }, { date: "2026-08-11", count: 25 }, { date: "2026-08-12", count: 27 }, { date: "2026-08-13", count: 6 }, { date: "2026-08-14", count: 10 }, { date: "2026-08-15", count: 0 }],
    [{ date: "2026-08-16", count: 0 }, { date: "2026-08-17", count: 3 }, { date: "2026-08-18", count: 10 }, { date: "2026-08-19", count: 2 }, { date: "2026-08-20", count: 13 }, { date: "2026-08-21", count: 0 }, { date: "2026-08-22", count: 0 }],
    [{ date: "2026-08-23", count: 2 }, { date: "2026-08-24", count: 6 }, { date: "2026-08-25", count: 12 }, { date: "2026-08-26", count: 10 }, { date: "2026-08-27", count: 15 }, { date: "2026-08-28", count: 15 }, { date: "2026-08-29", count: 7 }],
    [{ date: "2026-08-30", count: 0 }, { date: "2026-08-31", count: 0 }, { date: "2026-09-01", count: 0 }, { date: "2026-09-02", count: 10 }, { date: "2026-09-03", count: 25 }, { date: "2026-09-04", count: 15 }, { date: "2026-09-05", count: 11 }],
    [{ date: "2026-09-06", count: 6 }, { date: "2026-09-07", count: 33 }, { date: "2026-09-08", count: 6 }, { date: "2026-09-09", count: 0 }, null, null, null],
  ],
}
